### ISSUE TITLE
Data Attributes crashes for no reason

### ISSUE THREAD

**Issue by zoharTRP** [CleverNucleus/Data-Attributes#16] opened 2022-06-24 18:50 UTC
Crashy link with the details of the crash: [https://crashy.net/Oiw5h6RRMWLXWHe2vdeZ](url)
I originally had player ex installed as well but I removed it for testing purposes
Also if the only 2 mods I got installed are Data Attributes and fabric API it works

**Comment by CleverNucleus** [comment] 2022-06-24 19:34
Hi there,
Thank you for the report. Looking at the log I can see that this is a duplicate of #15; however, I can also see that Create for Fabric is not on the list of mods that were run. This is useful because it implies that create is not actually the mod conflicting with Data Attributes.

Therefore, even though this is technically a duplicate, I'm going to leave this open.

**Comment by zoharTRP** [comment] 2022-06-24 20:14
Okay, I was messing with the mods and just found out that the fabric version of the twilight forest (ver: 1.18.2-4.1.232) is making Minecraft crash. You should check if #15 uses this mod if not then I don't know maybe certain types of mods make the game crash.

**Comment by CleverNucleus** [comment] 2022-06-24 22:47
Interesting, I think you're probably correct: so far it seems mods that play about with attributes are incompatible. Obviously not ideal, considering the context of Data Attributes - I'll continue working on it.

**Comment by TropheusJ** [comment] 2022-06-25 23:16
This is a duplicate of #15, both Create and TF use Porting Lib, which is the actual cause.

**Comment by CleverNucleus** [comment] 2022-06-25 23:30
Hi there @TropheusJ,
I agree, and have just seen the null check commit to prevent crashing. I appreciate the quick catch on that.

I will continue to work on this issue however, as the attribute instance should not be null in the first place - Data Attributes is definitely messing something up, I cannot have all mods that add attributes implement a null check just to cover for my bug, after all 🤣.

**Comment by TropheusJ** [comment] 2022-06-25 23:32
See my comments on the [Create issue](https://github.com/Fabricators-of-Create/Create/issues/400) for info, I tracked it down.

**Comment by CleverNucleus** [comment] 2022-06-27 12:38
Fixed with release v1.1.8.

**Closed** 2022-06-27 12:37 UTC
Labels: bug
